[workspace]
resolver = "3"
members = [
    "cybird",
    "cybird-macro",
    "examples/clicker-plugin",
    "examples/crazier-crab",
    "examples/crypto-crab",
    "examples/rogue-game",
    "examples/rogue-lib",
]
